# permissions for end users to view dnsnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dnsnetworkpolicy-viewer-role
rules:
- apiGroups:
  - networking.volodymyrstoiko.com
  resources:
  - dnsnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.volodymyrstoiko.com
  resources:
  - dnsnetworkpolicies/status
  verbs:
  - get
